server:
  port: 8082
  servlet:
    session:
      timeout: 7200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hjk?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Maximum number of active connections that can be allocated from this pool at the same time.
    tomcat.max-active: 50
    # Number of ms to wait before throwing an exception if no connection is available.
    tomcat.max-wait: 10000

  transaction:
    rollback-on-commit-failure: true

  # REDIS (RedisProperties)
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis.pool.max-active: 8
    jedis.pool.max-wait: -1
    jedis.pool.max-idle: 8
    lettuce.pool.min-idle: 0
    # connet time out (ms)
    timeout: 5000
## logging
logging:
  level:
    root: info
    net.hyjuki.smgen.dao: debug

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.hyjuki.smgen.model